### ISSUE TITLE
Use of `ayon_common`

### ISSUE THREAD

**Issue by antirotor** [ynput/ayon-third-party#17]
### Is there an existing issue for this?

- [x] I have searched the existing issues and added correct labels.

## Current Behavior
This addon is still using some functionality from [ayon-launcher](ynput/ayon-launcher) - it is importing `ayon_common` that is available only there. I am not sure why it is working elsewhere, but when calling certain functions of **ayon-core** outside of "normal" flow, it crashes because of that. For example in unit tests testing some ayon-core functions.

## Expected Behavior
It shouldn't import module that isn't available.

### Steps To Reproduce:

Create some unit tests for ayon-core functions. I don't really know when this is getting triggered, but it will fail on import of `ayon_common`.

### Relevant log output:

```shell
=============================
No module named 'ayon_common'
=============================
Traceback (most recent call last):
  File "E:\projects\ynput\repos\ayon-core\client\ayon_core\addon\base.py", line 338, in _load_ayon_addons
    mod = __import__(basename, fromlist=("",))
  File "C:\Users\annat\AppData\Local\Ynput\AYON\addons\ayon_third_party_1.1.3-dev.1\ayon_third_party\__init__.py", line 3, in <module>
    from .addon import ThirdPartyDistAddon
  File "C:\Users\annat\AppData\Local\Ynput\AYON\addons\ayon_third_party_1.1.3-dev.1\ayon_third_party\addon.py", line 5, in <module>
    from .utils import (
  File "C:\Users\annat\AppData\Local\Ynput\AYON\addons\ayon_third_party_1.1.3-dev.1\ayon_third_party\utils.py", line 10, in <module>
    from ayon_common import (
ModuleNotFoundError: No module named 'ayon_common'
```

**Comment by antirotor** [comment]
This should be solved by #14
